name: Tests

on:
  workflow_dispatch:
  push:

jobs:
  swift_test:
    name: Test
    uses: AudioKit/ci/.github/workflows/swift_test.yml@main
    with:
      scheme: AudioKit
      platforms: iOS macOS
      swift-versions: 5.5
